### ISSUE TITLE
Artificial Intelligence and Accessibility Research Symposium 10 - 11 January 2023

### ISSUE THREAD

**Issue by ShreeshaBhat1004** [w3c/wai-about-wai#196]
Please publish the recordings and the transcripts of the symposium

**Comment by shawna-slh** [comment]
Hi @ShreeshaBhat1004 

We have an [in-progress draft page with the recordings](https://deploy-preview-193--wai-about-wai.netlify.app/about/projects/wai-coop/symposium2/) now.	

Please don't share that link because we will be changing some things (including the navigation).

We welcome your input on that page, e.g., is it clear? does the organization work for you? Feel free to [open an issue(s)](https://github.com/w3c/wai-about-wai/issues/new?title=AI-symposium) with your input.

**Comment by shawna-slh** [comment]
Hi @ShreeshaBhat1004 The share-able link is : https://www.w3.org/WAI/research/ai2023/
